### PR TITLE
allowance for lua function callbacks and infinite arguments

### PR DESCRIPTION
**Pull request by flashintv**

### CODE REVIEW

**Review by Unholywanderer — APPROVED** [review]
yes I think

**Comment by tposejank** [comment]
> yes I think

unholy this is the linc_luajit repo not psych engine

**Comment by Unholywanderer** [comment]
> > yes I think
> 
> unholy this is the linc_luajit repo not psych engine

I will smack you

**Comment by skruyo** [comment]
> > > yes I think
> > 
> > 
> > unholy this is the linc_luajit repo not psych engine
> 
> I will smack you

😈

**Comment by flashintv** [comment]
image
tested on psych engine, when said tween ends, it fires the inline function

**Review by MemeHoovy — APPROVED** [review]

**Review by mayo78 — APPROVED** [review]
@nebulazorua PLZ pull this it would be so awesome and cool

**Comment by mayo78** [comment]
why did the original version of linc_luajit not use reflect

**Comment by nebulazorua** [comment]
I really should check on these things more often LOL

**Comment by mayo78** [comment]
LATE BY 2 YEARS

**Comment by tposejank** [comment]
it is crazy out of every conversation in GitHub I've partaken participation in, i have to get notified by this

**Comment by flashintv** [comment]
2 years to notice, so long that im not even active anymore within the community

https://github.com/user-attachments/assets/14677625-af0c-445f-8252-d9f60eed932e

**Comment by nebulazorua** [comment]
> LATE BY 2 YEARS

Sorry!

**Pull request merged**
